/**
* Created by chip on 6/18/17.
* This case should return a complexity of 1
*/
component {
    public boolean function returnTrue()
    {
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        foo = true;
        return foo;
    }
}